version: '3.9'

services:
  db:
    container_name: postgres
    image: postgres:13.4
    environment:
      POSTGRES_USER: myusername
      POSTGRES_PASSWORD: mypassword
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    volumes:
      - db:/data/postgres
    networks:
      - db
    restart: unless-stopped
networks:
  db:
    driver: bridge
volumes:
  db: